services:
  - type: web
    name: litkom-bot
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: litkom-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true
    plan: starter

  - type: pserv
    name: litkom-db
    runtime: postgresql
    plan: starter
    disk:
      name: pgdata
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
